// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v2beta1

import (
	corev2beta1 "github.com/atomix/atomix-controller/pkg/apis/core/v2beta1"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpochClock) DeepCopyInto(out *EpochClock) {
	*out = *in
	out.Election = in.Election
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpochClock.
func (in *EpochClock) DeepCopy() *EpochClock {
	if in == nil {
		return nil
	}
	out := new(EpochClock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GossipClock) DeepCopyInto(out *GossipClock) {
	*out = *in
	if in.Logical != nil {
		in, out := &in.Logical, &out.Logical
		*out = new(LogicalClock)
		**out = **in
	}
	if in.Physical != nil {
		in, out := &in.Physical, &out.Physical
		*out = new(PhysicalClock)
		**out = **in
	}
	if in.Epoch != nil {
		in, out := &in.Epoch, &out.Epoch
		*out = new(EpochClock)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GossipClock.
func (in *GossipClock) DeepCopy() *GossipClock {
	if in == nil {
		return nil
	}
	out := new(GossipClock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GossipConfig) DeepCopyInto(out *GossipConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Clock.DeepCopyInto(&out.Clock)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GossipConfig.
func (in *GossipConfig) DeepCopy() *GossipConfig {
	if in == nil {
		return nil
	}
	out := new(GossipConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GossipConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GossipConfigList) DeepCopyInto(out *GossipConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GossipConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GossipConfigList.
func (in *GossipConfigList) DeepCopy() *GossipConfigList {
	if in == nil {
		return nil
	}
	out := new(GossipConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GossipConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GossipProtocol) DeepCopyInto(out *GossipProtocol) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GossipProtocol.
func (in *GossipProtocol) DeepCopy() *GossipProtocol {
	if in == nil {
		return nil
	}
	out := new(GossipProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GossipProtocol) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GossipProtocolList) DeepCopyInto(out *GossipProtocolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GossipProtocol, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GossipProtocolList.
func (in *GossipProtocolList) DeepCopy() *GossipProtocolList {
	if in == nil {
		return nil
	}
	out := new(GossipProtocolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GossipProtocolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GossipProtocolSpec) DeepCopyInto(out *GossipProtocolSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GossipProtocolSpec.
func (in *GossipProtocolSpec) DeepCopy() *GossipProtocolSpec {
	if in == nil {
		return nil
	}
	out := new(GossipProtocolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GossipProtocolStatus) DeepCopyInto(out *GossipProtocolStatus) {
	*out = *in
	if in.ProtocolStatus != nil {
		in, out := &in.ProtocolStatus, &out.ProtocolStatus
		*out = new(corev2beta1.ProtocolStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GossipProtocolStatus.
func (in *GossipProtocolStatus) DeepCopy() *GossipProtocolStatus {
	if in == nil {
		return nil
	}
	out := new(GossipProtocolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogicalClock) DeepCopyInto(out *LogicalClock) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogicalClock.
func (in *LogicalClock) DeepCopy() *LogicalClock {
	if in == nil {
		return nil
	}
	out := new(LogicalClock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalClock) DeepCopyInto(out *PhysicalClock) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalClock.
func (in *PhysicalClock) DeepCopy() *PhysicalClock {
	if in == nil {
		return nil
	}
	out := new(PhysicalClock)
	in.DeepCopyInto(out)
	return out
}
